### ISSUE TITLE
Type Error : bpy_struct.__new__(type) expected a single argument 

### ISSUE THREAD

**Issue by derekcbr** [Griperis/BlenderDataVis#34]
DataVis is a very useful Blender addon. And I want to change it into pure python script to generate charts instead.
For class bar_chart.py:
class OBJECT_OT_BarChart(OBJECT_OT_GenericChart):
It inherited from OBJECT_OT_GenericChart. When I call this class by python:
barchart=OBJECT_OT_BarChart()
It will pop up an error: Type Error : bpy_struct.__new__(type) expected a single argument 

Also after loading a csv file, how the new DataManager instance can be used by general class?
Can you help with this?
Thanks!

**Comment by Griperis** [comment]
I think that would be hard because it is built in its depths upon Blender Python API.
**OBJECT_OT_GenericChart** inherits from **bpy.types.Operator** which inherits **bpy_struct** and all properties for charts are defined using **bpy.types.PropertyGroup** which encapsulates a lot of get / set / update functionality and synchronization with UI.

**DataManager** class is a singleton. You instance it once and it keeps its state when u instance it in another place, check it out here: https://python-3-patterns-idioms-test.readthedocs.io/en/latest/Singleton.html

Btw, I am going to be releasing an updated version of the addon (definitely by end of the summer), implementing new data analysis in **DataManager**, so you maybe want to wait for this, because the API is going to improve a lot.

**Comment by derekcbr** [comment]
Great news! Looking forward to the new version!!!
